### ISSUE TITLE
Question: Why `lazyvim.config.options` is loaded via `lazyvim.plugins.config` not from `init.lua`?

### ISSUE THREAD

**Issue by boltlessengineer** [folke/LazyVim#13]
First, thank you for making great plugin manager and this easy-to-start template.

I wonder why `lazyvim.config.options` is loaded from `lazyvim.plugins.config` not directly from `init.lua`. In my understanding, it seems to load `config.options` before all plugins from `lazy`.

Then, is it fine to just put `require('lazy.config.options')` on top of `init.lua` file?

**Comment by folke** [comment]
Yes, you could do that too. The reason I put it there, is that this repo can also be used to extend from in your own config.

My own dots are built on top of  `LazyVim`. See here:
https://github.com/folke/dot/blob/1d192d62f8fa4b0d18fb2ef6b2e6c027f57453f1/config/nvim/lua/config/lazy.lua#L17
