### ISSUE TITLE
feature: border of float term

### ISSUE THREAD

**Issue by mathjiajia** [folke/LazyVim#14]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

add a border of float_term, with the same options as `lazy.nvim`

### Describe alternatives you've considered

maybe raise this request at `lazy.nvim` repo?

**Comment by folke** [comment]
I've refactored the floating cmd code both in lazy.nvim and LazyVim.
LazyVim now uses the same config of lazy for the ui, so if you'd set it up there with a border, then the border will be applied.

Alternatively, you can pass it as an option, so `require('lazyvim.util').float_term(nil, {border = "single"})`

**Comment by mathjiajia** [comment]
Thank you @folke 👍
