### ISSUE TITLE
feature: Disable autoformat when saving file.

### ISSUE THREAD

**Issue by jeircul** [folke/LazyVim#17]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Thanks for all your work, with this repo I have completely moved away from vs-code.
I like the auto-format on save function and I still want it to be default. But it would be convenient to be able to quickly toggle the function. There is probably a way to disable for "*.json" for example, but this would not help my workflow. 
Is there a quick way to toggle this function?  

### Describe the solution you'd like

A toggle function for enable/disable auto-format on save.

### Describe alternatives you've considered

:set eventignore=BufWritePre

**Comment by folke** [comment]
There's a key binding for that already. Leader t f

**Comment by jeircul** [comment]
Brilliant. Thanks you!

**Comment by Isti115** [comment]
For future reference, as of 2023-02-18 (version 1.11.0) the binding is `<Leader> u f`.

**Comment by SPYFF** [comment]
Is it possible to disable autoformat completely by default? Its annoying when I open a new sourcefile from telescope, autoformat turns on again.

**Comment by dixpac** [comment]
Same as @SPYFF is it possible to disable autoformat completely?

**Comment by rohit-kumar-j** [comment]
@SPYFF, @dixpac, This is what I use in my own config. I was looking at lazyvim for default autoformat toggle and came up with this. You can specify it like this in your `init.lua` to disable autoformat by default:

### (Note: This is not a LazyVim feature. I just do this in my `init.vim`)

```lua
-- User options go here
_G.User = {}

-- Either make this true or false. It checks this everytime you Enter neovim. and sets this by default.
User.autoformat = false 

vim.api.nvim_create_autocmd({ 'BufWritePre' }, {
    group = vim.api.nvim_create_augroup('User_Group', { clear = false }),
    pattern = "*",
    callback = function()
        if User.autoformat == true then
            if vim.o.filetype == 'help' then
                -- Obviously do not save file type `help`
                return
            else
                vim.lsp.buf.format()
                -- print("Formatted buffer and saved!")
            end
        else
            -- print("Saving file... Auto format disabled!")
            return
        end
    end
})

function _G.toggleAutoformat()
    if User.autoformat == true then
        User.autoformat = not User.autoformat
        print("Disabled format on save")
    else
        User.autoformat = not User.autoformat
        print("Enabled format on save")
    end
end

-- Toggle Format on save
vim.api.nvim_set_keymap('n', '<leader>F', ':lua toggleAutoformat()<CR>',
    { noremap = true, silent = true, desc = "Toggle Format on Save" })
```
