### ISSUE TITLE
bug: slow when leaving neovim

### ISSUE THREAD

**Issue by SingularisArt** [folke/LazyVim#18]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-5e1687e-dirty

### Operating system/version

Arch Linux

### Describe the bug

When I leave neovim, it takes so long for neovim to actually stop. Like this:

https://user-images.githubusercontent.com/57925294/211065656-b5bfe3c3-5e8d-4437-b1fa-dbc3b4aff550.mp4

Also, neovim is just generally slow. While I type, it takes a couple of milliseconds to display. Typically, neovim is behind an entire word. Like I finished pressing the keys for the word `hello` and I'm already typing `world` and neovim hasn't even displayed the entire word `hello`.

### Steps To Reproduce

1. `git clone --recursive https://github.com/SingularisArt/Singularis ~/Singularis`.
2. `mv ~/.config/nvim ~/.config/nvim-back-up`
3. `mv ~/Singularis/aspects/nvim/files/.config/nvim ~/.config/nvim`
4. `nvim`

### Expected Behavior

I'm expecting neovim to be very fast, or at least not this slow.

**Comment by folke** [comment]
Sorry, but I'm not going to debug your config, that's on you. LazyVim itself should be really fast and I see you're not using LazyVim itself.

**Comment by SingularisArt** [comment]
I'm using LazyVim. I cloned the repo, renamed a couple of the folders, and put it in my own repo. Here's my directory structure:
```
.
├── init.lua
├── lazy-lock.json
└── lua
    └── SingularisArt
        ├── config
        │   ├── autocmds.lua
        │   ├── colorscheme.lua
        │   ├── icons.lua
        │   ├── keymaps.lua
        │   ├── lazy.lua
        │   └── options.lua
        └── plugins
            ├── coding.lua
            ├── colorschemes
            │   ├── functions.lua
            │   └── init.lua
            ├── config.lua
            ├── core.lua
            ├── debugging.lua
            ├── editor.lua
            ├── filetypes.lua
            ├── git.lua
            ├── lsp
            │   ├── handlers.lua
            │   ├── init.lua
            │   ├── navigator.lua
            │   └── settings
            │       ├── clangd.lua
            │       └── ...
            ├── treesitter.lua
            ├── ui.lua
            └── util.lua
```
Do you have any idea on what could be causing this?

**Comment by folke** [comment]
You added a bunch of other plugins, so those might cause the slow-down.

If you see Neovim hanging at exit, that typically means some plugin is throwing an error during exit.

Try disabling Noice and see if that helps. Especially on nightly, Noice is not really stable due to the big TUI rework.

**Comment by murilorodelli** [comment]
The same thing is happening to me on linux mint. And I didn't changed anything... it's a pure clone of LazyVim repo and I only installed the dependencies for the official plugins, like NodeJS, etc

**Comment by enrodpre** [comment]
I just suffered from the same thing, even though I just installed LazyVim. I had some old-stinky-ass autocmd that was causing the issue.

vim.api.nvim_create_autocmd("BufUnload", {
  desc = "Last status succesful when unloading buffer",
  buffer = 0,
  callback = function()
    vim.opt.laststatus = 0
  end,
})

Hope this helps if anyone keeps getting this.

**Comment by samerickson** [comment]
I ran into this issue on Windows. Specifically, I noticed that the delay would not occur on the splash screen, but would appear whenever I opened a file. This issue made me suspect autocmds, so I tried closing Neovim using `noautocmd q` and sure enough the issue went away.

I found this https://vi.stackexchange.com/questions/19337/is-there-a-way-to-tell-what-autocmds-have-run while looking for a way to see all the autocmds that are running when I attempt to quit. This yielded:

```txt
Executing VimLeavePre Autocommands for "*"
autocommand <Lua 570: ~/AppData/Local/nvim-data/lazy/mason.nvim/lua/mason/init.lua:9>

autocommand <Lua 385: ~/scoop/apps/neovim-nightly/current/share/nvim/runtime/lua/vim/lsp.lua:808>

autocommand <Lua 229: ~/AppData/Local/nvim-data/lazy/diffview.nvim/lua/diffview/logger.lua:131>

Executing VimLeavePre Autocommands for "*"
autocommand <Lua 659: ~/AppData/Local/nvim-data/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:374>

Executing VimLeavePre Autocommands for "*"
autocommand <Lua 1096: ~/AppData/Local/nvim-data/lazy/noice.nvim/lua/noice/init.lua:58>

Executing VimLeavePre Autocommands for "*"
autocommand <Lua 954: ~/AppData/Local/nvim-data/lazy/nvim-cmp/lua/cmp/utils/async.lua:17>

Executing VimLeavePre Autocommands for "*"
autocommand <Lua 1223: ~/AppData/Local/nvim-data/lazy/persistence.nvim/lua/persistence/init.lua:43>

Executing command: "'pwsh' '-NoLogo' '-ExecutionPolicy' 'RemoteSigned' '-Command' '[Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();$PSDefaultParameterValues['Out-File:Encoding']='utf8';' 'git branch --show-current'"


chdir(C:\Users\erick\AppData\Local\nvim)
Writing ShaDa file "C:\Users\erick\AppData\Local\nvim-data\shada\main.shada"
Executing LspNotify Autocommands for "*"
autocommand <Lua 834: ~/scoop/apps/neovim-nightly/current/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:262>

Executing LspNotify Autocommands for "*"
autocommand <Lua 834: ~/scoop/apps/neovim-nightly/current/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:262>

Executing DiagnosticChanged Autocommands for "*"
autocommand <Lua 792: ~/AppData/Local/nvim-data/lazy/trouble.nvim/lua/trouble/sources/diagnostics.lua:70>

Executing DiagnosticChanged Autocommands for "*"
autocommand <Lua 792: ~/AppData/Local/nvim-data/lazy/trouble.nvim/lua/trouble/sources/diagnostics.lua:70>

Executing DiagnosticChanged Autocommands for "*"
autocommand <Lua 792: ~/AppData/Local/nvim-data/lazy/trouble.nvim/lua/trouble/sources/diagnostics.lua:70>
```

Now I have previously worked on attempting to improve the [Startup time of Powershell](https://samerickson.github.io/blog/2024-06-09-powershell-startup-time) but it seems like Microsoft thinks that ~1200-1800 for a shell start-up is acceptable. With this in mind, the following line stood out:

```
Executing command: "'pwsh' '-NoLogo' '-ExecutionPolicy' 'RemoteSigned' '-Command' '[Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();$PSDefaultParameterValues['Out-File:Encoding']='utf8';' 'git branch --show-current'"
```

This is an auto command from the [persistence.nvim](https://github.com/folke/persistence.nvim) plugin. To test this theory I disabled the persistence plugin, and the lag when quitting neovim disappeared. The lag is from `pwsh` taking ~1260ms just to launch and then `git branch --show-current` command would still need to run.

I ended up solving this issue by using https://www.nushell.sh/ for which there is an extra in LazyVim already (https://www.lazyvim.org/extras/lang/nushell):

```lua
  LazyVim.terminal.setup("nu")
```

Nushell has a start-up time of around 12ms so we have a 1.2-second improvement.
