### ISSUE TITLE
nvim crash by whichkey

### ISSUE THREAD

**Issue by balazssoltesz** [folke/LazyVim#4]
Hello, try the following:
- open a file
- press leader (space) (whichkey is opening) 
- wait a bit (1sec)
- press "f"

my NVIM v0.9.0-dev crashes after these steps. If i am fast enough and can press "leader + ft" really fast then neo-tree can open.

**Comment by folke** [comment]
nightly is broken right now due to TUI rework. Use stable or wait till its fixed upstream
