### ISSUE TITLE
Question: Why do you refer to mason just via "mason.nvim" instead of full name "williamboman/mason.nvim" in depedencies?

### ISSUE THREAD

**Issue by Shinzu** [folke/LazyVim#5]
Hello,

This questions refers to https://github.com/folke/LazyVim/blob/main/lua/lazyvim/plugins/lsp/init.lua#L9 . Im not sure why you do this this way.

**Comment by folke** [comment]
Beause I defined the spec for mason here https://github.com/folke/LazyVim/blob/79bb9e17da13da291dc2a210df4a1b17be1bd8f7/lua/lazyvim/plugins/lsp/init.lua#L64

A dep can be a full spec, or a name of an existing plugin
