### ISSUE TITLE
Use some other 'mini.nvim' modules?

### ISSUE THREAD

**Issue by echasnovski** [folke/LazyVim#7]
These significantly improve workflow even with default `require('mini.xxx').setup()`:
- [mini.ai](https://github.com/echasnovski/mini.ai)
- [mini.surround](https://github.com/echasnovski/mini.surround)

These are not so critical, but useful:
- [mini.align](https://github.com/echasnovski/mini.align) to interactively align things.
- [mini.indentscope](https://github.com/echasnovski/mini.indentscope) shows current indent scope (with animation) and provides texobject and motion based on indent. Should correctly work alongside 'lukas-reineke/indent-blankline.nvim'.

These are purely suggestions for something that might be missing from current plugin lineup.

**Comment by folke** [comment]
For sure!

You probably don't know this yet, but this config can actually be used in a personal config by extending it.

My own dots extend this config through lazy :) https://github.com/folke/dot/blob/7f80b2919f3fdfbf99f4d19b024f04f737f24e00/config/nvim/lua/config/lazy.lua#L17

In my dots, I did add ai and surround and I'm planning to move them to LazyVim too.

Might be good to add indentscope as an alternative to indentblankline with `enabled=false`. Users can then enable it in their config and disable indentblankline.

**Comment by folke** [comment]
didn't read your comment well on indentscope working together with indentblankline.

Even funnier is that I was looking how I could make an indent based text object with `mini.ai` today and it seems indentscope does that! :)

**Comment by echasnovski** [comment]
> For sure!
> 
> You probably don't know this yet, but this config can actually be used in a personal config by extending it.

Yeah, I know. It was more an opportunity for a *veeery subtle* mention of some other modules :)

> Even funnier is that I was looking how I could make an indent based text object with `mini.ai` today and it seems indentscope does that! :)

It certainly should be possible to some extent. I've planned for ages now to sit and implement specifications for some set of most common textobjects (buffer, line, comment, indent, etc.), but haven't decided on format (wiki page, or extend `gen_spec` of 'mini.ai', or create new module 'mini.ai_specs') and haven't gathered enough motivation for it.

But nevertheless, 'mini.indentscope' will have a more evolved implementation of indent textobject with customizable `MiniIndentscope.config.options`.

**Comment by echasnovski** [comment]
> I've added indentscope and surround in the meantime. I really like indentscope a lot!
> 
> Will add ai in a bit.

Nice, thanks!

To give you options. Although in 'mini.surround' I personally much prefer "prefixed" mappings (like with default `s` and yours `gz`), other popular option would be a 'tpope/vim-surround' approach with "suffixed" mappings (here is a [recommended setup](https://github.com/echasnovski/mini.nvim/blob/a2d436f4b8b7d59c0ebcf5a5fed39ccab0e68515/doc/mini-surround.txt#L463)). It is more limited, but many seem to have adopted it.

**Comment by folke** [comment]
Added ai as well in the meantime.
I prefer the prefixed option. Thanks for all your work on mini!

**Comment by echasnovski** [comment]
> Thanks for all your work on mini!

Likewise for... **all** those plugins :)
